spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: hai-ding
        uri: lb://hai-ding-service
        predicates:
        - Path=/hai-ding/**
        filters:
        - StripPrefix=1
        - name: UriAccessLimit
          args:
            patterns:
              - /swagger-ui*/**
#              - /hd/order/**
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2
            redis-rate-limiter.burstCapacity: 6
            key-resolver: "#{@remoteAddressKeyResolver}"